language: java
sudo: false
jdk:
  - oraclejdk8
os:
  - linux

cache:
  directories:
    - $HOME/.m2

env:
  - PROJECTS_TO_BUILD: "!diozero-provider-jdkdio10,!diozero-provider-jdkdio11,!diozero-imu-visualiser"

install: true
script: mvn --version && mvn package
#script: mvn --projects '!diozero-provider-jdkdio10,!diozero-provider-jdkdio11,!diozero-imu-visualiser' clean compile package install
#script: mvn ${MAVEN_OPTS} clean compile package install
#script: mvn --projects='${PROJECTS_TO_BUILD}' clean compile package install

#deploy:
#  on:
#    all-branches: true
#  provider: bintray
#  file: distribution/bintray.json
#  user: mattjlewis
#  key: $BINTRAY_API_KEY
